######## app下api+rpc ,  Before starting this project, start the environment that the project depends on docker-compose-env.yml #######

services:

  #前端网关nginx-gateay (只代理flashsale，admin-api不在这里做代理)
  # Front-end gateway nginx-gateway (Only agent flashsale，admin-api Do not be an agent here)
  nginx-gateway:
    image: nginx:1.21.5
    container_name: nginx-gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - flashsale_net
    depends_on:
      - flashsale

  #前端api + 业务rpc - Front-end API + business RPC
  flashsale:
    # docker-hub : https://hub.docker.com/r/lyumikael/gomodd
    # dockerfile: https://github.com/Mikaelemmmm/gomodd , If you are macOs m1\m2 use dockerfile yourself to build the image
    image: lyumikael/gomodd:v1.22.1
    container_name: flashsale
    environment:
      # 时区上海 - Timezone Shanghai
      TZ: Asia/Shanghai
      GOPROXY: https://goproxy.cn,direct
    working_dir: /go/flashsale
    volumes:
      - .:/go/flashsale
    privileged: true
    restart: always
    networks:
      - flashsale_net

networks:
  flashsale_net:
    external: true
    name: flash-sale-system_flashsale_net

